### ISSUE TITLE
Phonegap Build: Crashes on start (Android)

### ISSUE THREAD

**Issue by bananaGator** [ropilz/phonegap-parse-plugin#1]
Version 1.0 caused app crashing on Android (4.4.3 and 5.1.1) only when the phone wakes up (screen on) with the app completely exited. This was not an issue at all in iOS. With this new version (1.2), the app always crashes on load (not tested in iOS). Not just the first time, but every time the app is started.

My project uses PhoneGap Build with Cordova v3.7.0. The only thing that has changed when updating the plugin version is the version number within the config.xml. Looking through the repo, there are version numbers that conflict (1.3 vs 1.2), which may be an issue, but probably not the cause of the crashing.

The project is back to using v1.0, and tollerating the closed app crashing, but is not ideal for release. All of the other Parse push plugins in PGB are terrible, so I hope there's a quick easy solution for this! :)

**Comment by idlework** [comment]
This is due the lack of an application class implementation. 

Phonegap/Cordova doesn't define a custom android.app.Application, it only defines an android Activity. With an Activity alone, we should be able to receive PNs just fine while our app is running. However, if a PN arrives when the app is not running, the app will be automatically invoked, and this plugin's ParsePushPluginReceiver runs before the Activity class or any javascript code gets a chance to call Parse.initialize(). The result is a crash dialog. To fix this, do the following:

Define a custom Application class that calls Parse.initialize() in its onCreate method. This way, the Parse subsystem gets initialized before the PN-handling code runs. Crash avoided. In your application's Java source path, e.g., platforms/android/src/com/example/app, create a file named MainApplication.java and define it this way

``` java
package com.example.app;

import android.app.Application;
import com.parse.Parse;

public class MainApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        Parse.initialize(this, "YOUR_PARSE_APPID", "YOUR_PARSE_CLIENT_KEY");
    }
}
```

Now register MainApplication in AndroidManifest.xml so it's used instead of the default. In the <application> tag, add the attribute android:name="com.example.app.MainApplication". Obviously, you don't have to name your application class this way.

**Comment by ropilz** [comment]
@idlework the main idea of this plugin is to avoid the Application class so it is easy to build from phonegap build. I will look deeper into this issue and fix it

**Comment by idlework** [comment]
@ropilz true... you shouldn't create custom Application class and change the Manifest.xml. These should be generated. It was a quick solution so @bananaGator could go on with development. I'am also looking at this problem, when i find something i'll contact you or create a pull request.

**Comment by bananaGator** [comment]
Thanks, @idlework, but PhoneGap Build is a service that uses existing submitted plugins, and simply compiles everything together. There is no access to the back end code.

@ropilz thanks so much!

**Comment by idlework** [comment]
@bananaGator Ah... yes... Still if you really really want to, you could do it locally with the cli.

**Comment by bananaGator** [comment]
Any luck, @ropilz?

**Comment by bananaGator** [comment]
I am marking this as resolved. Thanks to commentary on an older commit, I was able to modify the android application config tag from the config.xml, and it no longer crashes.
